### ISSUE TITLE
SM version specified by .target is higher than default SM version assumed

### ISSUE THREAD

**Issue by MFrancesco** [Optiminer/OptiminerEquihash#11] opened 2017-11-20 18:35 UTC
The log says it all

[2017-11-20 19:34:42.669] [info] [GPU0] Device info: {"id": "0/0" "name": "GeForce GTX 950M" "platform": "Nvidia" "driver": "384.90"}
[2017-11-20 19:34:42.709] [error] Build Status: -2
[2017-11-20 19:34:42.709] [error] Build Log:
ptxas fatal   : SM version specified by .target is higher than default SM version assumed

**Comment by botdruff** [comment] 2017-11-23 06:23
This is a duplicate of issue #2.

**Closed** 2017-11-23 09:15 UTC
